version: 0.2

phases:
    install:
        commands:
            - echo Step 1/4 - Running install step commands...
            # - echo Configuring Docker...
            # - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
            # - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    pre_build:
        commands:
            - echo Step 2/4 - Running prebuild step commands...
    build:
        commands:
            - echo Step 3/4 - Running build step commands...
            - echo Build started on `date`
            # - echo Building and validating Docker files...
            # - docker-compose up -d --build
    post_build:
        commands:
            - echo Step 4/4 - Running post build step commands...
            # - echo Compressing the package...
            # - zip -r release.zip .
            # - echo Uploading to S3...
            # - aws s3 cp release.zip s3://martin-deployments/release.zip --region eu-west-2
            - echo Build completed on `date`
    artifacts:
        files:
            - '**/*'