# Spec 3.8 as of Docker engine 19.03.0 (2019-07)
version: '3.8'
services:

  # --- Webserver: Nginx
  nginx:
    image: nginx:1.23.0-alpine
    container_name: ${APPLICATION_NAME}-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  # --- PHP container: Project files
  php:
    image: ${ECR_REGISTRY}:${ECR_VER}
    container_name: ${APPLICATION_NAME}-php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app-network

  # --- Database: MariaDB
  db:
    image: mariadb:10.6.8
    container_name: ${APPLICATION_NAME}-db
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'db'
      MYSQL_PASSWORD: 'db'
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

# --- Docker Networks
networks:
  app-network:
    driver: bridge

# --- Volumes
volumes:
  dbdata:
    driver: local
